### PR TITLE
Fix crash when using fake `png` with 15 bytes

### PR DESCRIPTION
**Pull request by alobaili**
This PR does the following:
- Change the implementation of `loadFileData(path:)` so that when running tests in Xcode using ⌘+U doesn't crash.
- Change the mime type for `eot` files to the correct `application/vnd.ms-fontobject`.
- Provide a more accurate matcher for detecting the mime type for `eot` files.
- Prevent a crash when calling `Swime.mimeType(bytes:)` passing 15 bytes.

More details are provided in some of the commit messages.

### CODE REVIEW

**Comment by alobaili** [comment]
Greetings @sendyhalim,

I'm honored to be contributing to this repo. Please review and, if all is well, merge my PR.

Thank you!

**Comment by sendyhalim** [comment]
Hi @alobaili sorry for the delay, been really busy with work & life recenly 🙏 , really appreciate your contributions, thank you!

Anyways thanks for the unit tests also!

**Comment by alobaili** [comment]
@sendyhalim Glad to be of help. I have a small question:

I noticed the latest release for this package was last year.

Any plans to issue a new version tag so clients (including me) can benefit from this fix?

**Comment by sendyhalim** [comment]
Yep @alobaili I just released 3.0.8 and probably released 3.1.0 since there's other PR that adds new filetype

Please note I forgot to check with `pod lint` before pushing the tag 😅 .

**Pull request merged**
