### PR TITLE
Fixed deployment targets.

### PR DESCRIPTION
**Pull request by buh**
This changes will fix the project for Carthage.

### CODE REVIEW

**Comment by sendyhalim** [comment]
@buh thanks, looks like there's something wrong with the build. I haven't taken a look at this, but I guess there's something to do with the build config. I'm going to merge this first though.

**Comment by buh** [comment]
@sendyhalim Thanks! Could you please make a release `3.0.2`? It's important for Carthage.

**Comment by sendyhalim** [comment]
Oh right, I forgot to make the release, please try it https://github.com/sendyhalim/Swime/releases/tag/3.0.2

**Comment by buh** [comment]
@sendyhalim thanks! It works now.

**Pull request merged**
